# Generated by Django 4.0.1 on 2022-01-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworks',
            name='link',
            field=models.URLField(default='https://i.com/'),
        ),
    ]
