# Generated by Django 4.0.1 on 2022-01-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_technologies_icon_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='workflow',
            field=models.TextField(max_length=1000),
        ),
    ]
